- name : "Disable Old Version Of nodejs"
  ansible.builtin.command : "dnf module disable nodejs"

- name : "Enable Latest Varsion Of nodejs"
  ansible.built.command : "dnf module enable nodejs:20"

- name : "Installing nodejs"
  ansible.builtin.dnf :
    name : nodejs
    state : latest

- name : "Creating Application User"
  ansible.builtin.user :
   name : expense

- name : "Creating Location /app To Store Code"
  ansible.builtin.file:
   path : /app
   state : directory  

- name : "Download and Unarchive Code To /app" 
  ansible.builtin.unarchive :
   src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
   dest : /app
   remote_src : yes

- name : "Installing Dependencies For node App"
  community.general.npm:
   path : /app

