- name : Install nginx
  ansible.builtin.dnf :
   name : nginx
   state : latest

- name : Start And Enable nginx
  ansible.builtin.systemd_service :
   name : nginx
   state : started
   enabled : yes

- name : Remove Html Dir
  ansible.builtin.file :
   path : /usr/share/nginx/html
   state : absent

- name : Create Html Dir
  ansible.builtin.file :
   path : /usr/share/nginx/html
   state : directory

- name : Download and Unarchive Code
  ansible.builtin.unarchive:
    src : https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest : /usr/share/nginx/html
    remote_src: yes

- name : Copy Expense Config File
  ansible.builtin.template :
   src : expense.conf.j2
   dest : /etc/nginx/default.d/expense.conf

- name : Start And Enable nginx
  ansible.builtin.systemd_service :
   name : nginx
   state : restarted
   
    
  