- name : "Mysql Server Installation"
  ansible.builtin.dnf:
   name : mysql-server
   state : installed
  
- name : "Start And Enable mysqld service"
  ansible.builtin.systemd_service:
   name : mysqld
   state : started
   enabled : yes

- name : "Install Dependencies To Connect MYSQL"
  ansible.builtin.pip:
   name : "{{item}}"
   state : latest
   executable : pip3.9
  loop :
     - PyMySQL
     - cryptography
     
- name : "Check Connection With Server"
  community.mysql.mysql_info :
   login_user: "{{superuser}}"
   login_password:  "{{superuserpass}}"
   login_host : "{{loginhost}}"
   filter: version
  register : sqlerr
  ignore_errors : yes

- name : "Set Root Password"
  ansible.builtin.command : "mysql_secure_installation --set-root-pass {{superuserpass}}"
  when : sqlerr.failed is true